# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-08 08:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('va', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='ans',
            name='score',
        ),
        migrations.AddField(
            model_name='ans',
            name='awareness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ans',
            name='ease_of_discovery',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ans',
            name='ease_of_exploit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ans',
            name='financial_damage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ans',
            name='intrusion_detection',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ans',
            name='privacy_violation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ans',
            name='reputation_damage',
            field=models.IntegerField(default=0),
        ),
    ]
