# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-20 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('va', '0002_auto_20200308_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='va.Ques')),
            ],
        ),
    ]
