# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-20 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va', '0003_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='score_for_subpart',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ques',
            name='sub_part',
            field=models.CharField(default=b'NULL', max_length=200),
        ),
    ]
