# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-20 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('va', '0005_ques_ques_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='ques',
            new_name='ques_num',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
    ]
