# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-20 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('va', '0006_auto_20200321_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ans',
            name='ques',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='ques_num',
        ),
        migrations.RemoveField(
            model_name='score',
            name='ques',
        ),
        migrations.AddField(
            model_name='score',
            name='ques_num',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='va.Ques'),
        ),
        migrations.DeleteModel(
            name='Ans',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
