# Generated by Django 2.1.7 on 2020-03-31 15:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('va', '0007_auto_20200321_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(10, 'HIGH'), (5, 'MEDIUM'), (1, 'LOW')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AnsBunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 3, 31, 15, 22, 35, 888483, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='ques',
            name='score_for_subpart',
            field=models.IntegerField(choices=[(10, 'HIGH'), (5, 'MEDIUM'), (1, 'LOW')], default=0),
        ),
        migrations.AlterField(
            model_name='ques',
            name='sub_part',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='ans',
            name='bunch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_answers', to='va.AnsBunch'),
        ),
        migrations.AddField(
            model_name='ans',
            name='ques',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_answers', to='va.Ques'),
        ),
    ]
