# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-29 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va', '0007_auto_20200321_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ques',
            name='score_for_subpart',
            field=models.CharField(default=b'medium', max_length=10),
        ),
    ]
