# Generated by Django 2.1.7 on 2020-04-02 10:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('va', '0008_auto_20200331_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subpart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubpartAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='ans',
            name='score',
        ),
        migrations.RemoveField(
            model_name='ques',
            name='score_for_subpart',
        ),
        migrations.RemoveField(
            model_name='ques',
            name='sub_part',
        ),
        migrations.AlterField(
            model_name='ansbunch',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 10, 10, 6, 204693, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='subpartans',
            name='ans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subpart_answers', to='va.Ans'),
        ),
        migrations.AddField(
            model_name='subpartans',
            name='subpart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='va.Subpart'),
        ),
        migrations.AddField(
            model_name='subpart',
            name='ques',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_subparts', to='va.Ques'),
        ),
    ]
