# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-05 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('va', '0009_auto_20200402_1540'),
        ('va', '0009_auto_20200331_0335'),
    ]

    operations = [
    ]
