# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-06 00:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('va', '0010_merge_20200405_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansbunch',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 0, 34, 11, 865423, tzinfo=utc)),
        ),
    ]
